### ISSUE TITLE
AttributeError: 'CustomAuthToken' object has no attribute 'POST'

### ISSUE THREAD

**Issue by opswami** [jsocol/django-ratelimit#207]
Traceback (most recent call last):
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/ratelimit/decorators.py", line 20, in _wrapped
    increment=True)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/ratelimit/core.py", line 119, in is_ratelimited
    usage = get_usage(request, group, fn, key, rate, method, increment)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/ratelimit/core.py", line 180, in get_usage
    value = _ACCESSOR_KEYS[accessor](request, k)
  File "/home/om/python_env/perpule3/lib/python3.6/site-packages/ratelimit/core.py", line 62, in <lambda>
    'post': lambda r, k: r.POST.get(k, ''),
AttributeError: 'CustomAuthToken' object has no attribute 'POST'

code : 

class CustomAuthToken(ObtainAuthToken):

    @ratelimit(key='post:username', rate='2/m', block=True)
    @ratelimit(key='ip', rate='4/m', block=True)
    def post(self, request, *args, **kwargs):
        diff_id = 0
        ----

**Comment by jsocol** [comment]
As of 3.0, the `@ratelimit` [decorator can't be applied directly to class methods](https://django-ratelimit.readthedocs.io/en/latest/usage.html#class-based-views), you need to use the `@method_decorator` wrapper. There are [more details in the upgrading docs](https://django-ratelimit.readthedocs.io/en/latest/upgrading.html#ratelimit-decorator-on-class-methods).

Was this a new install or an upgrade?

**Comment by opswami** [comment]
Thanks I missed that point after upgrade but in some post request data are in request.data for me but ratelimit is trying to get data from request.POST, so here it is not giving any error but not working properly for those api

**Comment by jsocol** [comment]
Hmm, I know that happens with django-rest-framework, which wraps the Django `Request` object with its own custom class. Are you using DRF? If so, you probably need to either apply the decorator to the output of `MyApiView.as_view()` or use `ratelimit.core.is_ratelimited` with some custom code

**Comment by jsocol** [comment]
Closing for now but feel free to reopen if the workarounds in the last comment didn't help.
